version: "3"

services:
  web:
    image: nginx
    container_name: ccf_web
    ports:
      - 8000:80
    links:
     - php
     - database
    volumes:
      - ./server.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - ../src:/var/www/html

  php:
    build: ./php-fpm-composer
    container_name: ccf_php
    ports:
      - "9000:9000"
    volumes:
      - ../src:/var/www/html

  database:
    image: mariadb:latest
    container_name: ccf_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "../db:/var/lib/mysql"
    ports:
      - 8001:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ccf_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8002:80
    links:
      - database
