version: '3'

services:
  web:
    build:
      context: .
    container_name: ccf_web
    ports:
      - 8080:80
    volumes:
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ../src:/var/www/html:rw
    restart: always

  database:
    image: mariadb:latest
    container_name: ccf_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "../db:/var/lib/mysql"
    ports:
      - 8001:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ccf_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8002:80
    links:
      - database
